name: CodeShip
description: FullStack React Developers.
meta_description: ""

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://diihfilipe.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
cover: https://s3-us-west-2.amazonaws.com/codeshiplabs/codeshiplogo.jpeg
cover_width: 520px

# Details for the RSS feed generator
url:            'http://diihfilipe.github.io/'
author:         'Diego Araújo'
