name: KomodoDev
description: Um blog sobre desenvolvimento web e suas tecnologias.
meta_description: "KomodoDev desenvolvimento web."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: 
domain_name: 'http://komodotecnologia.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://diihfilipe.github.io/'
author:         'Diego Araújo'
