name: KomodoDev
description: Um blog sobre desenvolvimento web e suas tecnologias.
meta_description: "KomodoDev desenvolvimento web."

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://diihfilipe.github.io/'
google_analytics: 'UA-XXXXXXXX-X'
cover: http://bydigital.com.br/wp-content/uploads/2013/06/free-office-wallpaper-26001-26685-hd-wallpapers.jpg
cover_width: 520px

# Details for the RSS feed generator
url:            'http://diihfilipe.github.io/'
author:         'Diego Araújo'
